name: Feature Request
description: Suggest an idea for this repo.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: feature-problem
    attributes:
      label: What's the problem/gap?
      description: Is your feature request related to a problem, or a gap in the current capabilities of the repo?
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: desired-solution
    attributes:
      label: Desired Solution
      description: A clear and concise description of what you want to happen.
      placeholder: It would be good if [...]
    validations:
      required: true
  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: Have you consider any other alternative solutions and/or features?
      placeholder: I thought about [...], but [...]
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: When thinking about this feature, think about [...]